export {Login as Login} from "./Login"
export {Cadastro as Cadastro} from "./Cadastro"
export {Animais as Animais} from "./Animais"
export {Adicionar as Adicionar} from "./Adicionar"
export {Comprar as Comprar} from "./Comprar"